export const invoices = [
    {
        name: "Ashley Wilson",
        accNum: "ACC10000",
        accountType: "Checking",
        accountBalance: 9187.06,
        lastTransactionDate: "2023-08-17",
        overdraftStatus: "Yes",
        activeStatus: "Yes",
    },
    {
        name: "Teresa Young",
        accNum: "ACC10001",
        accountType: "Savings",
        accountBalance: 8478.26,
        lastTransactionDate: "2018-05-13",
        overdraftStatus: "No",
        activeStatus: "No",
    },
    {
        name: "Vincent Ward",
        accNum: "ACC10002",
        accountType: "Credit",
        accountBalance: 8343.97,
        lastTransactionDate: "2017-05-10",
        overdraftStatus: "No",
        activeStatus: "Yes",
    },
    {
        name: "Elizabeth Lopez",
        accNum: "ACC10003",
        accountType: "Checking",
        accountBalance: 4360.14,
        lastTransactionDate: "2018-03-02",
        overdraftStatus: "Yes",
        activeStatus: "Yes",
    },
    {
        name: "Louis Rivera",
        accNum: "ACC10004",
        accountType: "Savings",
        accountBalance: 978.34,
        lastTransactionDate: "2021-05-19",
        overdraftStatus: "No",
        activeStatus: "No",
    },
    {
        name: "Grace Alexander",
        accNum: "ACC10005",
        accountType: "Loan",
        accountBalance: 6903.18,
        lastTransactionDate: "2018-12-09",
        overdraftStatus: "Yes",
        activeStatus: "Yes",
    },
    {
        name: "Jeremy Walker",
        accNum: "ACC10006",
        accountType: "Checking",
        accountBalance: 3284.44,
        lastTransactionDate: "2023-04-29",
        overdraftStatus: "No",
        activeStatus: "No",
    },
    {
        name: "Brian Anderson",
        accNum: "ACC10007",
        accountType: "Savings",
        accountBalance: 724.13,
        lastTransactionDate: "2021-01-19",
        overdraftStatus: "Yes",
        activeStatus: "No",
    },
    {
        name: "Jeremy Walker",
        accNum: "ACC10008",
        accountType: "Savings",
        accountBalance: 5417.91,
        lastTransactionDate: "2019-03-08",
        overdraftStatus: "No",
        activeStatus: "Yes",
    },
    {
        name: "Michael Williams",
        accNum: "ACC10009",
        accountType: "Loan",
        accountBalance: 1387.39,
        lastTransactionDate: "2020-05-07",
        overdraftStatus: "No",
        activeStatus: "No",
    },
];
